
services:
  Files\Infrastructure\Controller\:
    resource: '%kernel.project_dir%/src/Files/Infrastructure/Controller'
    public: true
    autowire: true
    tags: [ 'controller.service_arguments' ]

  Files\Application\Command\SaveCommandFactory: ~

  Files\Application\Service\FileService:
    lazy: true
    arguments:
      - '%kernel.project_dir%/files'
      - '@Symfony\Component\Filesystem\Filesystem'
      - '@Files\Application\Dto\SaveFileDtoFactory'

  Files\Application\Service\FileServiceInterface: '@Files\Application\Service\FileService'

  Files\Application\Dto\SaveFileDtoFactory:
    arguments:
      - '%env(EXTERNAL_SERVICE_URL)%'
